// Mock data for WordPress Network management

export interface Site {
  id: number;
  name: string;
  url: string;
  status: 'active' | 'archived';
  health: 'excellent' | 'good' | 'warning' | 'critical';
  theme: string;
  lastUpdated: string;
  visits: number;
  uptime: number;
  wpVersion: string;
  plugins: number;
}

export interface AnalyticsData {
  date: string;
  visits: number;
  pageviews: number;
}

export interface ThemeInfo {
  name: string;
  version: string;
  sitesUsing: number;
  lastUpdate: string;
  status: 'updated' | 'outdated' | 'deprecated';
}

export interface PluginInfo {
  name: string;
  version: string;
  sitesUsing: number;
  updates: number;
  status: 'updated' | 'update-available' | 'critical';
}

export const sites: Site[] = [
  // Main Site
  {
    id: 1,
    name: 'College of Education Main Site',
    url: 'https://education.ufl.edu',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-20',
    visits: 85234,
    uptime: 99.9,
    wpVersion: '6.7',
    plugins: 24,
  },
  // Program Sites
  {
    id: 2,
    name: 'ESOL/Bilingual Education',
    url: 'https://education.ufl.edu/esol/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-18',
    visits: 12453,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 18,
  },
  {
    id: 3,
    name: 'Computer Science Education',
    url: 'https://education.ufl.edu/computer-science-education/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-15',
    visits: 8934,
    uptime: 99.4,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 4,
    name: 'Counselor Education',
    url: 'https://education.ufl.edu/counselor-education/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-21',
    visits: 15678,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 5,
    name: 'Early Childhood Education',
    url: 'https://education.ufl.edu/early-childhood/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-19',
    visits: 13452,
    uptime: 99.5,
    wpVersion: '6.7',
    plugins: 21,
  },
  {
    id: 6,
    name: 'Educational Technology',
    url: 'https://education.ufl.edu/educational-technology/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-22',
    visits: 18923,
    uptime: 99.9,
    wpVersion: '6.7',
    plugins: 22,
  },
  {
    id: 7,
    name: 'Educational Leadership',
    url: 'https://education.ufl.edu/educational-leadership/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-20',
    visits: 21456,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 8,
    name: 'Education Sciences',
    url: 'http://education.ufl.edu/education-sciences',
    status: 'active',
    health: 'warning',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-09-10',
    visits: 6234,
    uptime: 98.2,
    wpVersion: '6.6',
    plugins: 19,
  },
  {
    id: 9,
    name: 'Elementary Education',
    url: 'https://education.ufl.edu/elementary-education/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-17',
    visits: 16789,
    uptime: 99.6,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 10,
    name: 'English Education',
    url: 'https://education.ufl.edu/english-education/',
    status: 'active',
    health: 'good',
    theme: 'Enfold',
    lastUpdated: '2025-10-14',
    visits: 11234,
    uptime: 99.3,
    wpVersion: '6.7',
    plugins: 18,
  },
  {
    id: 11,
    name: 'Higher Education',
    url: 'https://education.ufl.edu/higher-education/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-19',
    visits: 14567,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 21,
  },
  {
    id: 12,
    name: 'Mathematics Education',
    url: 'https://education.ufl.edu/math-education/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-21',
    visits: 17890,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 22,
  },
  {
    id: 13,
    name: 'Reading and Literacy Education',
    url: 'https://education.ufl.edu/reading-education/',
    status: 'active',
    health: 'good',
    theme: 'Enfold',
    lastUpdated: '2025-10-16',
    visits: 12890,
    uptime: 99.4,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 14,
    name: 'Research and Evaluation Methodology',
    url: 'https://education.ufl.edu/research-evaluation-methodology/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-13',
    visits: 9876,
    uptime: 99.2,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 15,
    name: 'School Psychology',
    url: 'https://education.ufl.edu/school-psychology/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-20',
    visits: 19234,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 21,
  },
  {
    id: 16,
    name: 'Science Education',
    url: 'https://education.ufl.edu/science-education/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-18',
    visits: 15432,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 17,
    name: 'Science or Mathematics Teaching Certificate',
    url: 'https://education.ufl.edu/school-teaching-learning/science-mathematics-teaching-certificate/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-11',
    visits: 7890,
    uptime: 99.1,
    wpVersion: '6.7',
    plugins: 18,
  },
  {
    id: 18,
    name: 'Social Studies Education',
    url: 'https://education.ufl.edu/social-studies-education/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-19',
    visits: 13567,
    uptime: 99.6,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 19,
    name: 'Certificate Program in Secondary Teaching',
    url: 'https://education.ufl.edu/school-teaching-learning/secondary-teaching-certificate/',
    status: 'active',
    health: 'good',
    theme: 'Enfold',
    lastUpdated: '2025-10-12',
    visits: 8456,
    uptime: 99.3,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 20,
    name: 'Special Education',
    url: 'https://education.ufl.edu/special-education/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-21',
    visits: 22345,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 23,
  },
  {
    id: 21,
    name: 'Teacher Leadership for School Improvement',
    url: 'https://education.ufl.edu/tlsi/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-10',
    visits: 6789,
    uptime: 99.0,
    wpVersion: '6.7',
    plugins: 17,
  },
  {
    id: 22,
    name: 'Teachers, Schools, and Society',
    url: 'https://education.ufl.edu/curriculum-teaching/',
    status: 'active',
    health: 'good',
    theme: 'Enfold',
    lastUpdated: '2025-10-15',
    visits: 10234,
    uptime: 99.4,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 23,
    name: 'UF Teach',
    url: 'https://education.ufl.edu/uf-teach/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-20',
    visits: 14789,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 21,
  },
  // School Sites
  {
    id: 24,
    name: 'School of Teaching and Learning',
    url: 'https://education.ufl.edu/school-teaching-learning/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-22',
    visits: 28456,
    uptime: 99.9,
    wpVersion: '6.7',
    plugins: 24,
  },
  {
    id: 25,
    name: 'School of Human Development and Organizational Learning',
    url: 'https://education.ufl.edu/hdoas/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-21',
    visits: 25789,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 23,
  },
  {
    id: 26,
    name: 'School of Special Education, School Psychology and Early Childhood Studies',
    url: 'https://education.ufl.edu/sespecs/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-20',
    visits: 24567,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 22,
  },
  // Additional Sites (expanding to 50+)
  {
    id: 27,
    name: 'College of Education News',
    url: 'https://education.ufl.edu/news/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-22',
    visits: 32456,
    uptime: 99.9,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 28,
    name: 'College of Education Events',
    url: 'https://education.ufl.edu/events/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-18',
    visits: 18934,
    uptime: 99.5,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 29,
    name: 'Admissions',
    url: 'https://education.ufl.edu/admissions/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-21',
    visits: 42356,
    uptime: 99.9,
    wpVersion: '6.7',
    plugins: 25,
  },
  {
    id: 30,
    name: 'Graduate Programs',
    url: 'https://education.ufl.edu/graduate/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-19',
    visits: 35678,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 22,
  },
  {
    id: 31,
    name: 'Undergraduate Programs',
    url: 'https://education.ufl.edu/undergraduate/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-17',
    visits: 28934,
    uptime: 99.6,
    wpVersion: '6.7',
    plugins: 21,
  },
  {
    id: 32,
    name: 'Research Centers',
    url: 'https://education.ufl.edu/research/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-20',
    visits: 16789,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 33,
    name: 'Faculty & Staff Directory',
    url: 'https://education.ufl.edu/directory/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-22',
    visits: 22456,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 18,
  },
  {
    id: 34,
    name: 'Alumni Relations',
    url: 'https://education.ufl.edu/alumni/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-16',
    visits: 14567,
    uptime: 99.4,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 35,
    name: 'About the College',
    url: 'https://education.ufl.edu/about/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-21',
    visits: 26789,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 21,
  },
  {
    id: 36,
    name: 'Student Resources',
    url: 'https://education.ufl.edu/student-resources/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-19',
    visits: 31234,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 23,
  },
  {
    id: 37,
    name: 'Career Services',
    url: 'https://education.ufl.edu/career-services/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-14',
    visits: 18456,
    uptime: 99.3,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 38,
    name: 'Professional Development',
    url: 'https://education.ufl.edu/professional-development/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-18',
    visits: 12890,
    uptime: 99.6,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 39,
    name: 'Community Engagement',
    url: 'https://education.ufl.edu/community/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-15',
    visits: 10567,
    uptime: 99.2,
    wpVersion: '6.7',
    plugins: 18,
  },
  {
    id: 40,
    name: 'Diversity & Inclusion',
    url: 'https://education.ufl.edu/diversity/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-20',
    visits: 15234,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 41,
    name: 'Library Resources',
    url: 'https://education.ufl.edu/library/',
    status: 'active',
    health: 'good',
    theme: 'Enfold',
    lastUpdated: '2025-10-12',
    visits: 9876,
    uptime: 99.1,
    wpVersion: '6.7',
    plugins: 17,
  },
  {
    id: 42,
    name: 'Technology Support',
    url: 'https://education.ufl.edu/technology/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-21',
    visits: 13456,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 21,
  },
  {
    id: 43,
    name: 'International Programs',
    url: 'https://education.ufl.edu/international/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-13',
    visits: 8234,
    uptime: 99.0,
    wpVersion: '6.7',
    plugins: 18,
  },
  {
    id: 44,
    name: 'Scholarships & Financial Aid',
    url: 'https://education.ufl.edu/financial-aid/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-22',
    visits: 38456,
    uptime: 99.9,
    wpVersion: '6.7',
    plugins: 22,
  },
  {
    id: 45,
    name: 'Dean\'s Office',
    url: 'https://education.ufl.edu/deans-office/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-20',
    visits: 11234,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 46,
    name: 'Academic Advising',
    url: 'https://education.ufl.edu/advising/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-17',
    visits: 24567,
    uptime: 99.5,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 47,
    name: 'Online Learning',
    url: 'https://education.ufl.edu/online/',
    status: 'active',
    health: 'excellent',
    theme: 'Enfold',
    lastUpdated: '2025-10-19',
    visits: 27890,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 23,
  },
  {
    id: 48,
    name: 'Practicum & Field Experience',
    url: 'https://education.ufl.edu/field-experience/',
    status: 'active',
    health: 'good',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-11',
    visits: 15678,
    uptime: 99.3,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 49,
    name: 'Certification Programs',
    url: 'https://education.ufl.edu/certification/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-18',
    visits: 19234,
    uptime: 99.6,
    wpVersion: '6.7',
    plugins: 20,
  },
  {
    id: 50,
    name: 'Continuing Education',
    url: 'https://education.ufl.edu/continuing-education/',
    status: 'active',
    health: 'good',
    theme: 'Enfold',
    lastUpdated: '2025-10-14',
    visits: 12345,
    uptime: 99.2,
    wpVersion: '6.7',
    plugins: 18,
  },
  {
    id: 51,
    name: 'Partnerships & Collaborations',
    url: 'https://education.ufl.edu/partnerships/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Child Theme',
    lastUpdated: '2025-10-20',
    visits: 9876,
    uptime: 99.7,
    wpVersion: '6.7',
    plugins: 19,
  },
  {
    id: 52,
    name: 'Give to the College',
    url: 'https://education.ufl.edu/giving/',
    status: 'active',
    health: 'excellent',
    theme: 'Divi COE Faculty',
    lastUpdated: '2025-10-21',
    visits: 14890,
    uptime: 99.8,
    wpVersion: '6.7',
    plugins: 21,
  },
];

export const analyticsData: AnalyticsData[] = [
  { date: '10/15', visits: 28456, pageviews: 89234 },
  { date: '10/16', visits: 31234, pageviews: 95678 },
  { date: '10/17', visits: 27890, pageviews: 86543 },
  { date: '10/18', visits: 33456, pageviews: 102345 },
  { date: '10/19', visits: 26789, pageviews: 81234 },
  { date: '10/20', visits: 24567, pageviews: 75432 },
  { date: '10/21', visits: 29876, pageviews: 91234 },
  { date: '10/22', visits: 35678, pageviews: 108765 },
];

export const themes: ThemeInfo[] = [
  {
    name: 'Enfold',
    version: '5.6.10',
    sitesUsing: 18,
    lastUpdate: '2025-10-10',
    status: 'updated',
  },
  {
    name: 'Divi COE Child Theme',
    version: '4.2.1',
    sitesUsing: 17,
    lastUpdate: '2025-09-25',
    status: 'updated',
  },
  {
    name: 'Divi COE Faculty',
    version: '4.1.8',
    sitesUsing: 17,
    lastUpdate: '2025-08-15',
    status: 'outdated',
  },
];

export const plugins: PluginInfo[] = [
  {
    name: 'Yoast SEO',
    version: '22.0',
    sitesUsing: 52,
    updates: 0,
    status: 'updated',
  },
  {
    name: 'Advanced Custom Fields',
    version: '6.2.4',
    sitesUsing: 48,
    updates: 1,
    status: 'update-available',
  },
  {
    name: 'WP Super Cache',
    version: '1.9.8',
    sitesUsing: 45,
    updates: 0,
    status: 'updated',
  },
  {
    name: 'Contact Form 7',
    version: '5.8.2',
    sitesUsing: 50,
    updates: 2,
    status: 'critical',
  },
  {
    name: 'Wordfence Security',
    version: '7.11.2',
    sitesUsing: 52,
    updates: 0,
    status: 'updated',
  },
  {
    name: 'WPForms',
    version: '1.8.5',
    sitesUsing: 38,
    updates: 0,
    status: 'updated',
  },
  {
    name: 'Elementor',
    version: '3.18.2',
    sitesUsing: 15,
    updates: 1,
    status: 'update-available',
  },
  {
    name: 'Gravity Forms',
    version: '2.7.15',
    sitesUsing: 42,
    updates: 0,
    status: 'updated',
  },
];

export const networkStats = {
  totalSites: 52,
  activeSites: 52,
  totalVisits: 987654,
  avgUptime: 99.5,
  criticalIssues: 0,
  pendingUpdates: 4,
};
